#release configuration
#Tue Dec 10 00:19:58 CET 2024
completedPhase=scm-commit-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.de.webalf\:slotbotServer=0.0.1-SNAPSHOT
project.rel.de.webalf\:slotbotServer=2.15.0
project.scm.de.webalf\:slotbotServer.developerConnection=scm\:git\:https\://github.com/Alf-Melmac/slotbotServer.git
project.scm.de.webalf\:slotbotServer.tag=HEAD
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=v2.15.0
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:https\://github.com/Alf-Melmac/slotbotServer.git
